import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Spacer, Breadcrumbs, Table, Button, Link } from "@geist-ui/core"
import { ExternalLink } from "@geist-ui/icons"
import { useMemo } from 'react'
import setlist from '../json/setlist'



export async function getStaticProps() {
  return {
    props: {
      setlist
    }
  }
}


export default function Setlist(props) {



  const renderAction = (value, rowData, index) => {
    const removeHandler = () => {
      setData(last => last.filter((_, dataIndex) => dataIndex !== index))
    }
    return (
      <Button type="error" auto scale={1/3} font="12px" onClick={removeHandler}>Remove</Button>
    )
  }

  const generateSetUrl = (url) => {
    return <Link target="_blank" href={url} icon color></Link>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SBTP.XYZ - Setlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Setlist
        </h1>

        <Breadcrumbs>
          <Breadcrumbs.Item><Link href="/">Home</Link></Breadcrumbs.Item>
          <Breadcrumbs.Item>Setlist</Breadcrumbs.Item>
        </Breadcrumbs>

        <Spacer w={5}/>

        <Table data={props.setlist}>
          <Table.Column prop="setName" label="名前 (Name)" />
          <Table.Column prop="setAbbr" label="Abbr" />
          <Table.Column prop="setNameEn" label="Name" />
          <Table.Column prop="releaseDate" label="Release Date" />
        </Table>

      </main>

      <footer className={styles.footer}>
        <Link
          href="https://www.ebay.com/str/sakurablossomtradingpost"
          target="_blank"
        >
          eBay Store
        </Link>
        <Link
          href="https://twitter.com/ebay_sbtp"
          target="_blank"
        >
          Twitter
        </Link>
        <Link
          href="mailto:chris@sbtp.xyz"
          target="_blank"
        >
          E-Mail
        </Link>
      </footer>
    </div>
  )
}
